apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-2
  namespace: nginx-test2
spec:
  selector:
    matchLabels:
      run: nginx-test-2
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx-test-2
    spec:
      containers:
      - name: nginx-test-2
        image: nginx
        ports:
        - containerPort: 80

