apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Emanuel-Inf/GitOps-Test.git
    targetRevision: HEAD
    path: app-of-apps/argo-configs
  destination:
    server: https://kubernetes.default.svc
