apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-infrastruktur
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Emanuel-Inf/GitOps-Test.git
    targetRevision: HEAD
    path: traefik/infrastruktur/traefik-infrastruktur
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true
