apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Emanuel-Inf/GitOps-Test.git
    targetRevision: HEAD
    path: nginx-2
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-test1