apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Emanuel-Inf/GitOps-Test.git
    targetRevision: HEAD
    path: applikation
  destination:
    server: https://kubernetes.default.svc
    namespace: whoami