  name: Pull Request
  on:
    pull_request:
      branches: [ 'main' ]

  jobs:
    context:
      runs-on: ubuntu-latest
      steps:

        - name: Checkout
          uses: actions/checkout@v4
            
        - name: lint charts
          run: |
            cd charts/traefik-infrastruktur
            helm lint .