  name: Pull Request
  on:
    pull_request:
      branches: [ 'main' ]

  jobs:
    setup:
      runs-on: ubuntu-latest
      steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: lint charts
          run: |
            cd charts/traefik-infrastruktur
            helm lint .
    #    - name: setup-go
    #      uses: actions/setup-go@v4
    #      with:
    #        go-version: 1.21.4

    #    - name: setup-minikube
    #      id: minikube
    #      uses: medyagh/setup-minikube@master

    lint:
      runs-on: ubuntu-latest
      steps:

        - name: lint charts
          run: |
            cd charts/traefik-infrastruktur
            helm lint .

    #unit-tests:
    #  needs: setup
    #  runs-on: ubuntu-latest
    #  steps:

    #    - name: Install test dependencies
    #      run: |
    #        cd charts/test/unit-tests
    #        go mod download

    #    - name: run unit tests
    #      run: |
    #        cd charts/test/unit-tests
    #        go test

    #integration-tests:
    #  needs: setup
    #  runs-on: ubuntu-latest
    #  steps:

    #    - name: Install test dependencies
    #      run: |
    #        cd charts/test/integration-tests
    #        go mod download

    #    - name: run unit tests
    #      run: |
    #        cd charts/test/integration-tests
    #        go test