  name: Pull Request
  on:
    pull_request:
      branches: [ 'main' ]

  jobs:

    lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: lint charts
          run: |
            cd charts/traefik-infrastruktur
            helm lint .

    unit-tests:
      needs: lint
      runs-on: ubuntu-latest
      steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: setup-go
          uses: actions/setup-go@v4
          with:
            go-version: 1.21.4

        - name: Install test dependencies
          run: |
            cd charts/test/unit-tests
            go mod download

        - name: run unit tests
          run: |
            cd charts/test/unit-tests
            go test

    integration-tests:
      needs: lint
      runs-on: ubuntu-latest
      steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: setup-go
          uses: actions/setup-go@v4
          with:
            go-version: 1.21.4

        - name: setup-minikube
          id: minikube
          uses: medyagh/setup-minikube@master

        - name: Install test dependencies
          run: |
            cd charts/test/integration-tests
            go mod download

        - name: run unit tests
          run: |
            cd charts/test/integration-tests
            go test