  name: Pull Request
  on:
    pull_request:
      branches: [ 'main' ]

  jobs:
    context:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: setup-go
          uses: actions/setup-go@v4
          with:
            go-version: 1.21.4
        
        - name: Install dependencies
          run: |
            cd charts/test
            go mod download

        - name: run tests
          run: |
            cd charts/test
            go test